//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDaiwaForBPF.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConvertDaiwaForBPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   健診データが重複しています。個人番号：{0}　受信日：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_DUPLICATE_USER {
            get {
                return ResourceManager.GetString("E_DUPLICATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健診ヘッダーが空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_HDR_IS_EMPTY {
            get {
                return ResourceManager.GetString("E_HDR_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検査値が種別と合っていません。 項目名：{0}　種別：{1}　 検査値：{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_ITEM_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("E_ITEM_TYPE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目マッピングの順列の最大値と項目数（個数）が合っていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_ITEMMAPPING_INDEX_FAILE {
            get {
                return ResourceManager.GetString("E_ITEMMAPPING_INDEX_FAILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結合したデータが空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_MERGED_DATA_IS_EMPTY {
            get {
                return ResourceManager.GetString("E_MERGED_DATA_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健診データに該当ユーザーがいません。個人番号：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_NO_TDLDATA {
            get {
                return ResourceManager.GetString("E_NO_TDLDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   人事データに該当ユーザーがいません。個人番号：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_NO_USERDATA {
            get {
                return ResourceManager.GetString("E_NO_USERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目に値がありません。項目名：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_NOT_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("E_NOT_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健診ヘッダーが読めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_READFAILED_HDR {
            get {
                return ResourceManager.GetString("E_READFAILED_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイルが読めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_READFAILED_MASTER {
            get {
                return ResourceManager.GetString("E_READFAILED_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健診データが読めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_READFAILED_TDL {
            get {
                return ResourceManager.GetString("E_READFAILED_TDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   健診データが空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_TDL_IS_EMPTY {
            get {
                return ResourceManager.GetString("E_TDL_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CONVERT_FINISHED {
            get {
                return ResourceManager.GetString("MSG_CONVERT_FINISHED", resourceCulture);
            }
        }
    }
}
